# Generated by Django 4.2.4 on 2023-09-28 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_cid_app', '0002_remove_employees_phone_employees_phone_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='phone_numbers',
        ),
        migrations.AddField(
            model_name='employees',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
