# Generated by Django 4.2.4 on 2023-09-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_cid_app', '0003_remove_employees_phone_numbers_employees_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='computer_knowledge',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=3, null=True),
        ),
    ]
