# Generated by Django 4.2.4 on 2023-09-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_cid_app', '0004_alter_employees_computer_knowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='document_uploads/'),
        ),
    ]
