# Generated by Django 4.2.4 on 2023-09-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_cid_app', '0005_employees_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='document_upload_path'),
        ),
    ]
