# Generated by Django 4.2.4 on 2023-10-08 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_cid_app', '0008_alter_employees_dialogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='previous_trainings_done',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
