# Generated by Django 4.2.4 on 2023-10-08 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_cid_app', '0009_employees_previous_trainings_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='previous_positions_held',
            new_name='previous_positions_held_outside_cid',
        ),
        migrations.AddField(
            model_name='employees',
            name='previous_positions_held_within_cid',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
