# Generated by Django 4.2.4 on 2023-10-12 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_cid_app', '0013_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='security_question',
        ),
        migrations.AddField(
            model_name='customuser',
            name='admin_security_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_users', to='hrms_cid_app.adminsecurityquestion'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_security_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_users', to='hrms_cid_app.usersecurityquestion'),
        ),
    ]
