# Generated by Django 4.2.4 on 2023-10-12 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_cid_app', '0014_remove_customuser_security_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms_cid_app.employees'),
        ),
        migrations.AddField(
            model_name='user',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms_cid_app.employees'),
        ),
    ]
