# Generated by Django 4.2.4 on 2023-10-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_cid_app', '0016_customuser_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
