# Generated by Django 4.2.4 on 2023-10-13 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_cid_app', '0017_customuser_admin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='admin_id',
        ),
    ]
