# Generated by Django 4.2.4 on 2023-10-20 09:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_cid_app', '0018_remove_customuser_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportemployee',
            name='employee_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms_cid_app.rank'),
        ),
        migrations.AddField(
            model_name='leavereportemployee',
            name='leave_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
