# Generated by Django 4.2.4 on 2023-10-20 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_cid_app', '0019_leavereportemployee_employee_rank_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavereportemployee',
            old_name='employee_rank',
            new_name='rank',
        ),
    ]
