# Generated by Django 4.2.4 on 2023-10-20 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_cid_app', '0020_rename_employee_rank_leavereportemployee_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavereportemployee',
            old_name='rank',
            new_name='rank_id',
        ),
    ]
