# Generated by Django 4.2.4 on 2023-11-19 23:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_cid_app', '0022_alter_customuser_user_type_specialdg_sectionhead_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavereportemployee',
            name='rank_id',
        ),
        migrations.AddField(
            model_name='leavereportemployee',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavereportemployee',
            name='pid',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavereportemployee',
            name='rank',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
