# Generated by Django 4.2.4 on 2023-11-23 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_cid_app', '0023_remove_leavereportemployee_rank_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportemployee',
            name='employee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms_cid_app.employees'),
        ),
    ]
