# Generated by Django 4.2.4 on 2023-11-23 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_cid_app', '0025_alter_leavereportemployee_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms_cid_app.employees'),
        ),
    ]
