# Generated by Django 4.2.4 on 2023-11-23 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_cid_app', '0026_alter_leavereportemployee_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavereportemployee',
            name='employee',
        ),
    ]
