# Generated by Django 4.2.4 on 2023-12-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_cid_app', '0027_remove_leavereportemployee_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportemployee',
            name='ddo_approval_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavereportemployee',
            name='division_head_approval_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavereportemployee',
            name='section_head_approval_status',
            field=models.IntegerField(default=0),
        ),
    ]
