# Generated by Django 4.2.4 on 2023-12-07 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_cid_app', '0028_leavereportemployee_ddo_approval_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavereportemployee',
            name='leave_status',
        ),
    ]
