# Generated by Django 4.2.4 on 2023-12-10 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_cid_app', '0030_leavereportemployee_special_dg_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportemployee',
            name='division',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavereportemployee',
            name='section',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
