# Generated by Django 4.2.4 on 2023-12-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_cid_app', '0032_employees_other_emp_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCorrReq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('corr_req', models.TextField()),
                ('corr_req_reply', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
