# Generated by Django 4.2.4 on 2023-12-17 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_cid_app', '0035_profilecorrreq_division_profilecorrreq_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecorrreq',
            name='column_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilecorrreq',
            name='correct_value',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilecorrreq',
            name='current_value',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
