# Generated by Django 4.2.4 on 2024-01-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_cid_app', '0038_igp'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='cpis',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
