# Generated by Django 4.2.4 on 2024-01-06 21:32

from django.db import migrations, models
import django.db.models.deletion
import hrms_cid_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_cid_app', '0040_alter_employees_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedEmployees',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profile_pic', models.FileField(upload_to='')),
                ('gender', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('tehsil', models.TextField()),
                ('district', models.CharField(max_length=50)),
                ('parentage', models.TextField()),
                ('mother_name', models.TextField()),
                ('belt_no', models.TextField()),
                ('pid_no', models.TextField()),
                ('cpis', models.TextField()),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to=hrms_cid_app.models.document_upload_path)),
                ('date_appointment_police', models.DateField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('aadhar_number', models.CharField(max_length=50, unique=True)),
                ('pan_number', models.CharField(max_length=50, unique=True)),
                ('previous_positions_held_within_cid', models.TextField()),
                ('previous_positions_held_outside_cid', models.TextField()),
                ('qualifications', models.TextField()),
                ('dialogue', models.CharField(default='Null', max_length=9)),
                ('adverse_report', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('computer_knowledge', models.CharField(blank=True, default='No', max_length=3, null=True)),
                ('computer_degree', models.CharField(default='None', max_length=7)),
                ('computer_skill', models.CharField(default='None', max_length=9)),
                ('previous_trainings_done', models.TextField()),
                ('other_emp_info', models.TextField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('division_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms_cid_app.divisions')),
                ('rank_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms_cid_app.rank')),
                ('section_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms_cid_app.sections')),
                ('supervisor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms_cid_app.supervisor')),
            ],
        ),
    ]
