# Generated by Django 4.2.4 on 2024-01-07 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_cid_app', '0041_archivedemployees'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hrms_cid_app.divisions'),
            preserve_default=False,
        ),
    ]
