# Generated by Django 4.2.4 on 2024-01-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_cid_app', '0044_employees_casual_leave_counter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='casual_leave_reset_year',
        ),
    ]
