# Generated by Django 4.2.4 on 2024-01-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_cid_app', '0045_remove_employees_casual_leave_reset_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='committed_leave_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employees',
            name='earned_leave_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employees',
            name='paternity_maternity_leave_counter',
            field=models.IntegerField(default=0),
        ),
    ]
