# Generated by Django 4.2.4 on 2024-01-14 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_cid_app', '0047_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportemployee',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms_cid_app.notification'),
        ),
    ]
