# Generated by Django 4.2.4 on 2024-01-14 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_cid_app', '0048_leavereportemployee_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavereportemployee',
            name='notification',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
