# Generated by Django 4.2.4 on 2024-01-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_cid_app', '0049_remove_leavereportemployee_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'User'), (3, 'Section Head'), (4, 'Division Head'), (5, 'DDO'), (6, 'Special DG'), (7, 'IGP')], default=1, max_length=10),
        ),
    ]
